
spring:
  application:
    name: assessment
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/assessment
    username: root
    password: 120120
    hikari:
      maximum-pool-size: 4
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create